### PR TITLE
Fix for #22 & #23 & #20

### PR DESCRIPTION
**Pull request by syky27**
Disable scrolling when presenting on UITableViewController

### CODE REVIEW

**Comment by syky27** [comment]
10cd4b07235c8be71ff05a8a7c0e89f8e204a6e0 duplicates #24

**Comment by syky27** [comment]
Updated Pull request, `containerView.center` doesn't depend on view that is given, and new condition determining whenever, viewController is actually "under" UINavigationController

Added dummy viewController to test this new behaviour.

**Comment by web-melt** [comment]
Just tested to see if #23 is solved. It is. Didn't get around to test #22 right now.

**Comment by syky27** [comment]
For past 5 years what I develop iOS apps I have never ever used storyboard in my life. So I added test on NavigationController, but for the love of god I have not been able to center it using constraints in StoryBoard.

**Comment by web-melt** [comment]
Created a pull request to your repo.. hope this is the right way to alter a pull request not authored by oneself.

**Pull request merged**
